name: Pull Request Verification

on:
  pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  UPX_VERSION: 4.2.4
  CCACHE_VERSION: 4.10.2
  # needed because wiRenderer uses conditional include via __hasinclude
  CCACHE_NODIRECT: 1

jobs:

  linux:
    name: Linux (${{ matrix.shaders.type }} shaders)
    strategy:
      matrix:
        shaders:
          - type: optimized
            sc_args:
          - type: unoptimized
            sc_args: disable_optimization

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Restore Ccache database
      id: restore-ccache
      uses: actions/cache/restore@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.run_id }}
        restore-keys: ccache-

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libsdl2-dev ccache

    - name: Initial compile
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        make -j$(nproc) offlineshadercompiler

    - name: Generate shader dump
      run: |
        cd build/WickedEngine
        ./offlineshadercompiler spirv rebuild shaderdump ${{ matrix.shaders.sc_args }}
        mv wiShaderDump.h ../../WickedEngine/

    - name: Recompile with shader dump
      run: |
        cd build
        make -B -j $(nproc)

    - name: Save Ccache database
      id: save-ccache
      if: always() && steps.restore-ccache.cache-hit != 'true' && matrix.shaders.type == 'optimized'
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/ccache
        key: ${{ steps.restore-ccache.outputs.cache-primary-key }}

    - name: Move binaries
      run: |
        mv build/Editor/WickedEngineEditor ./Editor_Linux
        mv Editor/config.ini ./
        mv Editor/startup.lua ./
        mv Editor/languages ./
        mv Editor/fonts ./

    - name: Install official UPX
      run: |
        curl -sOSL https://github.com/upx/upx/releases/download/v$UPX_VERSION/upx-$UPX_VERSION-amd64_linux.tar.xz
        tar xf upx-$UPX_VERSION-amd64_linux.tar.xz upx-$UPX_VERSION-amd64_linux/upx

    - name: Compress Editor with UPX
      run: upx-$UPX_VERSION-amd64_linux/upx --best Editor_Linux

    - name: Package Editor
      uses: actions/upload-artifact@v4
      with:
        name: Editor (Linux, ${{ matrix.shaders.type }} shaders)
        path: |
          languages/
          fonts/
          config.ini
          startup.lua
          Editor_Linux

